# -*- coding: utf-8 -*-
"""runner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_qoJ2JMRXsDP-6WCoXjYx1ba4fjhVozK
"""

# Commented out IPython magic to ensure Python compatibility.
# # Cell 1: The Final, Simple, and Robust Installation
# %%capture
# from google.colab import drive
# import os
# 
# drive.mount('/content/drive')
# 
# print(">>> STEP 1: Installing the latest Unsloth package...")
# !pip install "unsloth[colab-new]" -U
# 
# print("\n>>> STEP 2: Performing targeted downgrade of Triton for T4 compatibility...")
# !pip uninstall -y triton
# !pip install triton==3.2.0
# 
# print("\n✅ Final Installation complete.")

# Commented out IPython magic to ensure Python compatibility.
# Cell 2: Login, Configuration & Paths
from google.colab import drive
from huggingface_hub import login
import os

# --- 1. Mount Drive (if session was restarted) ---
# try:
#     drive.mount('/content/drive', force_remount=False)
# except:
#     pass

# --- 2. Login to Hugging Face ---
from google.colab import userdata
hf_token = userdata.get('HF_TOKEN').strip()
login(token=hf_token)
os.environ["HUGGING_FACE_TOKEN"] = hf_token
print("✅ Logged in to Hugging Face successfully.")
# %cd /content/drive/MyDrive/NexusProject

# --- 3. Define Core Configuration ---
# We define these once, so both training and evaluation use the same values.
base_path = "/content/drive/MyDrive/NexusProject"
model_name = "deepseek-ai/deepseek-coder-7b-instruct"
dataset_name = "Abhishekcr448/Hinglish-Everyday-Conversations-1M"
output_dir = "outputs/DeepSeek-Hinglish-FINAL"

import sys
python_executable = sys.executable
base_path = "/content/drive/MyDrive/NexusProject"

# --- DEFINE YOUR HUB REPO ID ---
# IMPORTANT: Replace "YourHFUsername" with your actual Hugging Face username.
hf_repo_id = "Maitreya-04/DeepSeek-Hinglish-Test-FINAL"

!{python_executable} -m ml_scripts.fine_tune_prod \
    --base_path="{base_path}" \
    --hf_repo_id="{hf_repo_id}" \
    --output_dir="outputs/DeepSeek-Hinglish-FINAL" \
    --model_name="deepseek-ai/deepseek-coder-7b-instruct" \
    --dataset_name="Abhishekcr448/Hinglish-Everyday-Conversations-1M" \
    --dataset_split="train[:10000]" \
    --chat_template="chatml" \
    --max_steps=100 \
    --save_steps=50

